### ISSUE TITLE
Implement method "get_attestations" on WS API?

### ISSUE THREAD

**Issue by bonustrack** [byteball/byteballcore#100]
Would you consider adding a method on the node WS API to request attestations array for a specific address(es)?

Why? I'm working on a project that require attestations data (byteball.co) i'm already storing data on an external database but this give a single point of failure. I would like to create a software that can be used by 3p apps or individual where attestations data would be required. I want the software to not rely on a centralized db, i wish there is a method on the official node to query attestations.

**Comment by translationsproxy** [comment]
We already have `light/get_attestation` which is used by the wallets.  If it is not enough, feel free to submit a PR, I think it should be fairly easy to extract all attestations by address.

**Comment by tonyofbyteball** [comment]
We already have `light/get_attestation` which is used by the wallets. If it is not enough, feel free to submit a PR, I think it should be fairly easy to extract all attestations by address.

**Comment by tonyofbyteball** [comment]
I added it, it will be used in several bots

**Comment by bonustrack** [comment]
Awesomeness, thank you @tonyofbyteball
