### ISSUE TITLE
"Uncaught exception: TypeError: Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by guttermonk** [byteball/byteballcore#114]
After opening the wallet I receive the above mentioned error. When I click "OK", the wallet closes. Using the latest Byteball wallet 2.4.1.

Same issue as reported here, but I'm running Ubuntu 18.04 LTS instead of Windows: https://steemit.com/byteball/@stimialiti/my-sad-experience-with-the-byteball-airdrops-and-with-cryptocurrencies-exchanges

**Comment by tonyofbyteball** [comment]
This bug did affect full wallets that were only starting to sync, it was fixed in 2.4.2, please upgrade.
