### ISSUE TITLE
Question: Can user change a shared_address's definition by sending a definition_change unit ?

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [byteball/byteballcore#139]
If I make a shared_address with someone, and we all can use the money in it, so we all can compose unit with this address, right? So I am thinking, if I can compose a definition_change unit to change this shared_address's definition so the other one will no longer be able to use this address.

And another question came out. Whether a shared_address's definition can be used in definition_change unit to be an another address's new definition?

**Comment by Papabyte** [comment]
1. It should be possible.
If you look at validation code: https://github.com/byteball/byteballcore/blob/a0b18418d14c3b6ea74c1c76d3b749f77213be3d/validation.js#L1152
Any address that is in objUnit.authors can have its definition changed, whatever it's a shared one or not.

2. When you create a new definition, only chash is posted in DAG, the definition is posted later when you sign an unit with this address for a first time. So there would be no way to know wether the chash is from a shared_address's definition or not, thus it's certainly possible.
