### ISSUE TITLE
Some errors when initializing mysql

### ISSUE THREAD

**Issue by smartpunter** [byteball/byteballcore#32]
Tried this on fresh installation on Ubuntu 16.04

For table pairing_secrets: "Invalid default value for 'expiry_date'"
Solution: change "expiry_date TIMESTAMP NOT NULL" to "expiry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"

For table wallet_signing_paths: "All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead"
Solution: change "PRIMARY KEY (wallet, signing_path)," to "UNIQUE KEY (wallet, signing_path),"

For table shared_address_signing_paths: "All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead"
Solution: change "PRIMARY KEY (shared_address, signing_path)" to  "UNIQUE KEY (shared_address, signing_path)"

Hope this helps.

**Comment by smartpunter** [comment]
Another problem, when running byteball:

Error: ER_MIX_OF_GROUP_FUNC_AND_FIELDS: In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'byteball.peer_host_urls.url'; this is incompatible with sql_mode=only_full_group_by

You should tell, to disable only_full_group_by in config.

**Comment by smartpunter** [comment]
Another thing, to establish connection to mysql i should put connection details to conf.json.
But after initializing byteball, it overwrites it with object containing only deviceName!
So the connection details are lost and i have to read them manually, otherwise the node would not start.

**Comment by smartpunter** [comment]
Another database error, when i paired device:

failed query: SELECT SUM(total) AS total FROM (
                                SELECT SUM(amount) AS total FROM my_addresses CROSS JOIN witnessing_outputs USING(address) WHERE is_spent=0 AND wallet='*******'
                                UNION ALL
                                SELECT SUM(amount) AS total FROM my_addresses CROSS JOIN headers_commission_outputs USING(address) WHERE is_spent=0 AND wallet='*******' )
/home/byteball/byteballd/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_DERIVED_MUST_HAVE_ALIAS: Every derived table must have its own alias
    at Query.Sequence._packetToError (/home/byteball/byteballd/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)

**Comment by smartpunter** [comment]
Again, when issuing command 'pay' to bot.

failed query: SELECT address, SUM(amount) AS total
                FROM outputs JOIN my_addresses USING(address)
                CROSS JOIN units USING(unit)
                WHERE wallet='xxxx AND is_stable=1 AND sequence='good' AND is_spent=0 AND asset IS NULL
                        AND NOT EXISTS (
                                SELECT * FROM unit_authors JOIN units USING(unit)
                                WHERE is_stable=0 AND unit_authors.address=outputs.address AND definition_chash IS NOT NULL
                        )
                GROUP BY address ORDER BY (total>1100) DESC, ABS(total-1100) ASC
Error: ER_ILLEGAL_REFERENCE: Reference 'total' not supported (reference to group function)
 at readFundedAddresses (/home/byteball/byteballd/node_modules/byteballcore/wallet.js:967:5)

This query is just won't work, maybe we can omit order by?

**Comment by tonyofbyteball** [comment]
Thank you for finding these issues and proposing solutions for the newer mysql versions (we tested only on mysql 5.5 and even that long time ago).
* primary keys fixed
* ER_MIX_OF_GROUP_FUNC_AND_FIELDS: the query rewritten
* added alias for the temp table
* Regarding "ORDER BY (total>1100) DESC, ABS(total-1100) ASC" could you try replacing total with SUM(amount)?
* Rewriting of conf.json: yes the script shouldn't rewrite it, the bug belongs to headless-wallet though

**Comment by smartpunter** [comment]
You forgot about 

For table pairing_secrets: "Invalid default value for 'expiry_date'"
Solution: change "expiry_date TIMESTAMP NOT NULL" to "expiry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"

Will try Sum(amount), it should work, i suppose, will confirm later.

**Comment by tonyofbyteball** [comment]
Thanks, fixed that too

**Comment by smartpunter** [comment]
"Regarding "ORDER BY (total>1100) DESC, ABS(total-1100) ASC" could you try replacing total with SUM(amount)?"
Confirm, this code works : "ORDER BY (SUM(amount)>1100) DESC, ABS(SUM(amount)-1100) ASC"

**Comment by smartpunter** [comment]
Occasionaly, it throws an error:
at /home/byteball/BetByteBall/node_modules/byteballcore/headers_commission.js:29:10
```
failed query: INSERT INTO headers_commission_contributions (unit, address, amount)
                                        SELECT punits.unit, address, punits.headers_commission AS hc
                                        FROM units AS chunits
                                        JOIN unit_authors USING(unit)
                                        JOIN parenthoods ON chunits.unit=parenthoods.child_unit
                                        JOIN units AS punits ON parenthoods.parent_unit=punits.unit
                                        JOIN units AS next_mc_units ON next_mc_units.is_on_main_chain=1 AND next_mc_units.main_chain_index=punits.main_chain_index+1
                                        WHERE chunits.is_stable=1
                                                AND +chunits.sequence='good'
                                                AND punits.main_chain_index>104349
                                                AND chunits.main_chain_index-punits.main_chain_index<=1
                                                AND +punits.sequence='good'
                                                AND punits.is_stable=1
                                                AND next_mc_units.is_stable=1
                                                AND chunits.unit=( SELECT unit
                                        FROM parenthoods
                                        JOIN units AS alt_child_units ON parenthoods.child_unit=alt_child_units.unit
                                        WHERE parent_unit=punits.unit AND alt_child_units.main_chain_index-punits.main_chain_index<=1 AND +alt_child_units.sequence='good'
                                        ORDER BY SHA1(CONCAT(alt_child_units.unit, next_mc_units.unit))
                                        LIMIT 1 )
                                                AND (SELECT COUNT(*) FROM unit_authors WHERE unit=chunits.unit)=1
                                                AND (SELECT COUNT(*) FROM earned_headers_commission_recipients WHERE unit=chunits.unit)=0
                                        UNION ALL
                                        SELECT punits.unit, earned_headers_commission_recipients.address,
                                                ROUND(punits.headers_commission*earned_headers_commission_share/100.0) AS hc
                                        FROM units AS chunits
                                        JOIN earned_headers_commission_recipients USING(unit)
                                        JOIN parenthoods ON chunits.unit=parenthoods.child_unit
                                        JOIN units AS punits ON parenthoods.parent_unit=punits.unit
                                        JOIN units AS next_mc_units ON next_mc_units.is_on_main_chain=1 AND next_mc_units.main_chain_index=punits.main_chain_index+1
                                        WHERE chunits.is_stable=1
                                                AND +chunits.sequence='good'
                                                AND punits.main_chain_index>104349
                                                AND chunits.main_chain_index-punits.main_chain_index<=1
                                                AND +punits.sequence='good'
                                                AND punits.is_stable=1
                                                AND next_mc_units.is_stable=1
                                                AND chunits.unit=( SELECT unit
                                        FROM parenthoods
                                        JOIN units AS alt_child_units ON parenthoods.child_unit=alt_child_units.unit
                                        WHERE parent_unit=punits.unit AND alt_child_units.main_chain_index-punits.main_chain_index<=1 AND +alt_child_units.sequence='good'
                                        ORDER BY SHA1(CONCAT(alt_child_units.unit, next_mc_units.unit))
                                        LIMIT 1 )
Error: ER_DUP_ENTRY: Duplicate entry 'tCG7u76JJFvP4LTo1A1Hb3i8J01e47DebdG9edIKa0c=-UENJPVZ7HVHM6QGVGT6' for key 'PRIMARY'
```

Solution: use either INSERT IGNORE, or REPLACE, whatever suits best.

insert ignore - if key/row exists, skip insertion
replace - if key/row exists, delete the match row, and insert again

**Comment by tonyofbyteball** [comment]
> Confirm, this code works : "ORDER BY (SUM(amount)>1100) DESC, ABS(SUM(amount)-1100) ASC"
thanks, updated

**Comment by tonyofbyteball** [comment]
> Error: ER_DUP_ENTRY: Duplicate entry

It shouldn't happen.  Make sure you are not running two instances of your node at the same time.

**Comment by smartpunter** [comment]
Of course i am not, but sometimes you need to start/stop daemon, and that could be the cause.
Although it shouldn't happen, it may happen, and i believe it is a good idea to fix it, as easy as add 'INSERT IGNORE' to mysql requests.

**Comment by smartpunter** [comment]
So, another two days of waiting and i got this:

```
failed query: INSERT INTO known_bad_joints (unit, json, error) VALUES ('j/dC62enrCskmhoJUcvufIlF7q6PlqVBmTDi6dRRiL8=','{\"unit\":{\"version\":\"1.0\",\"alt\":\"1\",\"messages\":[{\"app\":\"data_feed\",\"payload_location\":\"inline\",\"payload_hash\":\"BV/rW3sib+7jnd7sUHJmp/4lNChEddwfmJo7hlhIAkI=\",\"payload\":{\"timestamp\":1496506189377}},{\"app\":\"payment\",\"payload_location\":\"inline\",\"payload_hash\":\"IgSJySgWnDWaA+uI0LeF1ERY9msS6iNdQoF7cMK5nSo=\",\"payload\":{\"outputs\":[{\"amount\":23,\"address\":\"I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT\"}],\"inputs\":[{\"unit\":\"CH3HfoBNRr/+AhCdmxHogkSbPSdMAIOghPGhtcUfEVs=\",\"message_index\":1,\"output_index\":0},{\"type\":\"headers_commission\",\"from_main_chain_index\":505426,\"to_main_chain_index\":505436},{\"type\":\"witnessing\",\"from_main_chain_index\":169986,\"to_main_chain_index\":170004}]}}],\"authors\":[{\"address\":\"I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT\",\"authentifiers\":{\"r\":\"tlIFCme+t2DufjDhwmekBEivXLaCFXAL+BSanrQLMfUG0/9jTFK0vO2mdKr3GqxcGKMJq8tyP+PrK8v3vvJAyg==\"}}],\"parent_units\":[\"v7JhuAKPLKsXC3uUSgLRmV3l1l5lVjbNGIJtiSQ1vZE=\"],\"last_ball\":\"IS5lP6T5z7ZW3tokLDe/vLviw2ZgLXrbjCbPyvD7sLY=\",\"last_ball_unit\":\"2mNmkHUjC8ppK3zTJNXzHgIJaDQAsFW09iMI98A2BI0=\",\"witness_list_unit\":\"oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=\",\"headers_commission\":344,\"payload_commission\":284,\"unit\":\"j/dC62enrCskmhoJUcvufIlF7q6PlqVBmTDi6dRRiL8=\",\"timestamp\":1496506189}}','some of the unit\'s parents are known bad: **THIS PHRASE WAS HERE 1560 times** some of the unit\'s parents are known bad: ')
Error: ER_DATA_TOO_LONG: Data too long for column 'error' at row 1

```

And after this there were some additional errors with duplicate entry to INSERT INTO headers_commission_contributions 

And then it just was exiting immediately affter start with

Error: known bad csbufrzlQvce0p3MiYzcDiT/daukyjxw8FeVyxOoSdg=: 
    at Error (native)
    at Object.ifKnownBad (/home/byteball/BetByteBall/node_modules/byteballcore/network.js:725:12)

I guess, i need to start syncing node to mysql for third time...

**Comment by tonyofbyteball** [comment]
> INSERT INTO known_bad_joints

This bug was fixed today (there are two of you who are syncing on mysql for the first time), please `npm update` and `DELETE FROM known_bad_joints`

**Comment by tonyofbyteball** [comment]
> Although it shouldn't happen, it may happen, and i believe it is a good idea to fix it, as easy as add 'INSERT IGNORE' to mysql requests.

It is intentional that the app crashes when something that shouldn't happen happens.  This way, we immediately know about the issues, fix them, and go ahead.
