### ISSUE TITLE
'new_my_transactions' never fired

### ISSUE THREAD

**Issue by smartpunter** [byteball/byteballcore#33]
I tried to follow the manual and make a basic chat bot, but unfortunately, i wasn't able to control incoming transactions.
I was succesfully issuing new addresses for new users, but when they send byte to this addresses, no events were fired at all.

I used fresh install Ubuntu 16.04 with sqlite database (because mysql had some errors here and there).

And there is no documentation to figure out, what is happening and what are the possible solutions.

Really sad, that such a great idea is being developed by only one person, of course it is impossible to develop, promote and carefully document such pretty complicated software.

**Comment by tonyofbyteball** [comment]
3 times more than 1 person (not counting contributors).

Make sure your node is fully synced.  Sync is a replay of the entire history, new transactions are added to the end of the history, and your node should reach that point in history in order to receive the event.

**Comment by smartpunter** [comment]
I left note to sync for one day, sqlite database is around 1.5GB, it didn't work... How to check, whether the node is fully synced?

**Comment by smartpunter** [comment]
Got this on slack:
"It looks like you are using the live net, my live db is about 3.8GB. I usually check the last main chain index to see the sync status:

```Select max(main_chain_index) from units;
```
And check this against the latest unit on the Byteball explorer"

So need to leave for another day or so.
