### ISSUE TITLE
Node can not be synced

### ISSUE THREAD

**Issue by smartpunter** [byteball/byteballcore#36]
Getting this error:

Error: known bad 1o1lmOCb2Fs5aa9q1BuvkqPXQTc7b+sDvMgC7QMC5f0=: too many (2) witness list mutations relative to MC unit e1luhU51xhFer3UMBoIVVQ+QfdMNRTUpjJ/6a94H9Pc=
    at Object.ifKnownBad (/home/byteball/BetByteBall/node_modules/byteballcore/network.js:725:12)
 
I deleted the base and decided to start again... There is nothing anyone can do with database, once it gets this kind of error. I believe it should be handled properly, so the node could continue to sync.

**Comment by tonyofbyteball** [comment]
a recent update fixes it as discussed in https://github.com/byteball/byteballcore/issues/32
