### ISSUE TITLE
calculation of MinMcWitnessedLevel

### ISSUE THREAD

**Issue by SeienK** [byteball/byteballcore#40]
It seems that duplicate witnesses will not be ignored when calculate the min_wl in function findMinMcWitnessedLevel(handleMinMcWl)

**Comment by tonyofbyteball** [comment]
what is *duplicate* witnesses?

**Comment by SeienK** [comment]
I mean the units posted by the same witness.

**Comment by SeienK** [comment]
I mean the units posted by the same witnesses.



when calculating the witnessed level of  a unit as below , arrCollectedWitnesses is maintained to avoid counting the same witness

----------------------------------------------------------------------------

function addWitnessesAndGoUp(start_unit){
profiler.start();
storage.readStaticUnitProps(conn, start_unit, function(props){
profiler.stop('write-wl-select-bp');
var best_parent_unit = props.best_parent_unit;
var level = props.level;
if (level === null)
throw Error("null level in updateWitnessedLevel");
if (level === 0) // genesis
return setWitnessedLevel(0);
profiler.start();
storage.readUnitAuthors(conn, start_unit, function(arrAuthors){
profiler.stop('write-wl-select-authors');
profiler.start();
for (var i=0; i<arrAuthors.length; i++){
var address = arrAuthors[i];
if (arrWitnesses.indexOf(address) !== -1 && arrCollectedWitnesses.indexOf(address) === -1)
arrCollectedWitnesses.push(address);
}
profiler.stop('write-wl-search');
(arrCollectedWitnesses.length < constants.MAJORITY_OF_WITNESSES)
? addWitnessesAndGoUp(best_parent_unit) : setWitnessedLevel(level);
});
});
}
-----------------------------------------------------------------------------------------------------------------------------


but when calculating the min_wl, it seems that there is not any measures to deal the same thing

-----------------------------------------------------------------------------------------------------------------------------

function findMinMcWitnessedLevel(handleMinMcWl){
var min_mc_wl = Number.MAX_VALUE;
var count = 0;

function goUp(start_unit){
conn.query(
"SELECT best_parent_unit, witnessed_level, \n\
(SELECT COUNT(*) FROM unit_authors WHERE unit_authors.unit=units.unit AND address IN(?)) AS count \n\
FROM units WHERE unit=?", [arrWitnesses, start_unit],
function(rows){
if (rows.length !== 1)
throw Error("findMinMcWitnessedLevel: not 1 row");
var row = rows[0];
if (row.count > 0 && row.witnessed_level < min_mc_wl)
min_mc_wl = row.witnessed_level;
count += row.count;
(count < constants.MAJORITY_OF_WITNESSES) ? goUp(row.best_parent_unit) : handleMinMcWl(min_mc_wl);
}
);
}

conn.query(
"SELECT witnessed_level, best_parent_unit, \n\
(SELECT COUNT(*) FROM unit_authors WHERE unit_authors.unit=units.unit AND address IN(?)) AS count \n\
FROM units \n\
WHERE unit IN(?) \n\
ORDER BY witnessed_level DESC, \n\
level-witnessed_level ASC, \n\
unit ASC \n\
LIMIT 1",
[arrWitnesses, arrLaterUnits],
function(rows){
var row = rows[0];
if (row.count > 0)
min_mc_wl = row.witnessed_level;
count += row.count;
goUp(row.best_parent_unit);
}
);
}
-----------------------------------------------------------------------------------------------------------------------------




________________________________

**Comment by tonyofbyteball** [comment]
This function just finds the minimum witnessed level along the MC.  How is it affected by duplicate witnesses?

**Comment by SeienK** [comment]
But when does it stop? It does not find the min witnessed level of all the units along the MC. It stops when it finds the majority of witness along the MC. Then my question is on the progress on finding the majority of witness along the MC. In this progress, duplicate witness will also only be recorded once in my opinion. But the code seems records every witnessed unit it meets.


________________________________

**Comment by tonyofbyteball** [comment]
You are correct, thanks for finding the error, this is fixed in https://github.com/byteball/byteballcore/commit/5f309283fef7fbd772bacadf2ceed1a3b50ec8fb
