### ISSUE TITLE
Missing break instruction in wallet_defined_by_addresses.js 

### ISSUE THREAD

**Issue by yaryribero** [byteball/byteballcore#41]
See line 345.

This bug causes an exception in case an address definition contains a 'r set of' and needs approval by multiple users because the missing break let the switch continue to evaluate possibilities until it meets its end (throw exception).

Found while trying to implement payments with shared addresses.

I fixed it locally by adding the missing 'break'. I am extensively analysing the core: if you granted me the right to branch and create pull requests I'd be glad to provide ready solutions together with bug notifications.

Best regards,

Yary

**Comment by tonyofbyteball** [comment]
Fixed https://github.com/byteball/byteballcore/commit/46d37fdfc09ceee629c902734879def51029481c

You can fork and create PRs, you don't need any permissions.

**Comment by yaryribero** [comment]
Thank you, tested and it works.
