### ISSUE TITLE
NakedUnit calculation is not explicit about fields

### ISSUE THREAD

**Issue by fitzn** [byteball/byteballcore#51]
In `object_hash.js`, the `getNakedUnit` function makes a deep copy of the provided `objUnit` and then deletes several fields that are not to be included in what constitutes a "naked unit".  This runs the risk of leaving extraneous fields from `objUnit` that should not be included when passing the resulting "naked unit" to other functions such as, `getBase64Hash`.

On the one hand, it's possible to argue that `getNakedUnit` operates this way to be a "cleaning" function for excluding certain known fields. However, given how the code uses `getNakedUnit`, it's clear that it is intended to prepare the `objUnit` for hashing. As a result, failing to remove rogue fields will influence the unit's hash and corrupt the result.

One possible solution would be to not use a `deep copy + delete`, but instead construct a new object and selectively copy all fields from `objUnit` that should be present. This approach protects from the issue above and has the additional benefit of being explicit about what fields *should* be in a valid "naked unit", which makes it easier to reason about.

**Comment by tonyofbyteball** [comment]
it's actually good that it fails when there are extraneous fields, so we'll know it immediately.  validation.js also checks for them.

**Comment by fitzn** [comment]
Okay - my intuition is that the hashes will fail to line up but they will "silently" without any indication of failing. Units will hash to different values without warning.

Feel free to resolve this issue, though, as I may be misunderstanding.

**Comment by fitzn** [comment]
I see now. ```validation.js:validate``` throws an Exception (```callbacks.ifUnitError```) on unknown fields being present.

This makes sense. I do feel it's easier to reason about the unit's hash inputs if they are explicitly copied but that's a style question, I suppose, not a correctness question.

Resolving this.
