### ISSUE TITLE
enable Circle CI so that tests run against main repo

### ISSUE THREAD

**Issue by thedavidmeister** [byteball/byteballcore#56]
Currently circle is running tests against my fork but doesn't seem to be running against pull requests for the main repo - e.g. https://github.com/byteball/byteballcore/pull/55

**Comment by thedavidmeister** [comment]
@tonyofbyteball would you be able to look at this? should just be a matter of turning it on in circle under your account.

**Comment by tonyofbyteball** [comment]
turned it on now, something didin't work the first time I tried
