### ISSUE TITLE
"Error: not 1 unit" when checking witnessed level

### ISSUE THREAD

**Issue by pmiklos** [byteball/byteballcore#61]
The following error is thrown when the witnessed level of the genesis unit is checked.
```
checkWitnessedLevelAndReplace 3gLI9EnI2xe3WJVPwRg8s4CB24ruetuddS0wYa2EI3c=
/root/node_modules/byteballcore/storage.js:1297
			throw Error("not 1 unit");
			^

Error: not 1 unit
    at /root/node_modules/byteballcore/storage.js:1297:10
    at Statement.<anonymous> (/root/node_modules/byteballcore/sqlite_pool.js:113:6)
```

It looks like [this recent commit](https://github.com/byteball/byteballcore/commit/cb513a3171976f113f57fa1eba2936772dc188ec#commitcomment-25794715) introduced it. See more details in the comment I added there.

**Comment by tonyofbyteball** [comment]
I have no idea why it was set to null, fixed https://github.com/byteball/byteballcore/commit/5e1928f2c2380121c299eaa40d519bb03ea8fb81
