### ISSUE TITLE
ERROR 1022 (23000) at line 724: Can't write; duplicate key in table 'attested_fields'

### ISSUE THREAD

**Issue by pmiklos** [byteball/byteballcore#92]
The latest `byteball.sql` fails to execute on Mysql database:

```
ERROR 1022 (23000) at line 724: Can't write; duplicate key in table 'attested_fields'
```

The problem is that constraint `attestationsByAttestorAddress` is already used in table `attestations`.

Also the `unit` field in tables `attested_fields` and `original_addresses` needs the BINARY keyword:
```
	unit CHAR(44) BINARY NOT NULL,
```

**Comment by tonyofbyteball** [comment]
Thanks fixed, I always forget BINARY
