### ISSUE TITLE
Error: Looks like you are loading multiple copies of byteballcore, which is not supported.

### ISSUE THREAD

**Issue by Odan316** [byteball/byteballcore#93]
I'm trying to start write script for issuing new asset, following instructions provided in wiki [here](https://github.com/byteball/byteballcore/wiki/Issuing-assets-on-Byteball)

I write only three lines of code and getting this error

```
"use strict";

var headlessWallet = require('headless-byteball');
var composer = require('byteballcore/composer.js');
```

I'm pretty new to npm and Node.js and maybe i'm making something completely wrong, but as I understand problem is in calling conf.js at byteballcore package by both 'require' commands, with first command setting 

`global._bByteballCoreLoaded = true`

by 

`require('./enforce_singleton.js');`

**Comment by Edie47** [comment]
Hello, unfortunatelly I am facing the same error with file _event_bus.js_ with this code:
`"use strict";
var eventBus = require('byteballcore/event_bus.js');
var headlessWallet = require('headless-byteball');`

Have you figured out the sollution?

**Comment by Odan316** [comment]
Hi, I have found workaround, but i'm not sure if it's my mistake all along, or should be corrected in byteball architecture.

Instead of 

```
"dependencies": {
	"headless-byteball": "git+https://github.com/byteball/headless-byteball.git",
	"byteballcore": "^0.2.33",
	.....
}
```
as stated in documentation, i write

```
"dependencies": {
    "headless-byteball": "git+https://github.com/byteball/headless-byteball.git",
    "byteballcore": "git+https://github.com/byteball/byteballcore.git",
    .....
  }
```
in my package.json

In this case, npm will not duplicate "byteballcore" package inside "headless-byteball" module and headless-byteball will use base byteballcore insteaad of creating second instance with his own package.

Maybe it should be changed in documentation.

**Comment by Edie47** [comment]
Thank you. It works.

**Comment by tonyofbyteball** [comment]
Headless now depends on git version of byteballcore, like suggested in your workaround, so the error should not appear again, at least if using node 6.x or later.
