### ISSUE TITLE
function pickParentUnits has no logic to ensure unit serial when number of free good sequence units large than 2 * MAX_PARENTS_PER_UNIT

### ISSUE THREAD

**Issue by gaoxiangxyz** [byteball/byteballcore#94]
function pickParentUnits only select first MAX_PARENTS_PER_UNIT free good sequence units order by unit. It seems that if number of free good sequence units larger than (2 * MAX_PARENTS_PER_UNIT), there is no logic to ensure unit serial.

For example, there is 32 free units(unit1 ... unit32), they have same parent. I send a new unit A and unit1 ...unit16 are selected as parents, then I send another unit B, it may select unit17 ... unit32 as parents, so now unit A and B are non serial units

**Comment by tonyofbyteball** [comment]
You are correct, it is possible.  In this case, validation will find that the unit is nonserial and the unit will not be saved or broadcasted.  When retried, the DAG will probably change and the next attempt might succeed.

**Comment by gaoxiangxyz** [comment]
@tonyofbyteball Thanks

**Comment by gaoxiangxyz** [comment]
@tonyofbyteball  It seems the best parent checked in function adjustParentsToNotRetreatWitnessedLevel may be excluded by arrAdjustedParents.slice(0, constants.MAX_PARENTS_PER_UNIT).
Is it better to record the best parent and make sure it will be in final returned parent list?

**Comment by tonyofbyteball** [comment]
You are correct, the commit above fixes this.
